<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;


class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $districts=[
            // 1 Dodoma
            ['district_name'=>'Kondoa',
             'region_id'=>1,
             'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mpwapwa',
             'region_id'=>1,
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),    
            ],
            ['district_name'=>'Kongwa',
             'region_id'=>1,
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Chamwino',
             'region_id'=>1,
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Dodoma Mjini',
             'region_id'=>1,
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Bahi',
             'region_id'=>1,
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Chemba',
             'region_id'=>1,
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],

            // 2 Arusha
            ['district_name'=>'Monduli',
             'region_id'=>2,
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Meru',
             'region_id'=>2,
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Arusha Mjini',
             'region_id'=>2,
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Karatu',
            'region_id'=>2,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ngorongoro',
            'region_id'=>2,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Arusha',
            'region_id'=>2,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Longido',
            'region_id'=>2,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 3 Kilimanjaro
            ['district_name'=>'Rombo',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mwanga',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Same',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Moshi',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Hai',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Moshi Municipal',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Siha',
            'region_id'=>3,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 4 Tanga
            ['district_name'=>'Lushoto',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Korogwe',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Muheza',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Tanga',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Pangani',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Handeni',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kilindi',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mkinga',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Korogwe Township Authority',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Handeni Township Authority',
            'region_id'=>4,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 5 Morogoro
            ['district_name'=>'Kilosa',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Morogoro',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kilombero',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ulanga',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Morogoro Mjini',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mvomero',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Gairo',
            'region_id'=>5,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 6 Pwani
            ['district_name'=>'Bagamoyo',
            'region_id'=>6,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kibaha',
            'region_id'=>6,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kisarawe',
            'region_id'=>6,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mkuranga',
            'region_id'=>6,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Rufiji',
            'region_id'=>6,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kibaha Mjini',
            'region_id'=>6,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 7 Dar-es-salaam
            ['district_name'=>'Kinondoni',
            'region_id'=>7,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ilala',
            'region_id'=>7,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Temeke',
            'region_id'=>7,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kigamboni',
            'region_id'=>7,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ubungo',
            'region_id'=>7,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 8 Lindi
            ['district_name'=>'Kilwa',
            'region_id'=>8,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Lindi Vijijini',
            'region_id'=>8,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Nachingwea',
            'region_id'=>8,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Liwale',
            'region_id'=>8,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ruangwa',
            'region_id'=>8,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Lindi Mjini',
            'region_id'=>8,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 9 Mtwara
            ['district_name'=>'Mtwara Vijijini',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Newala',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Masasi',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Tandahimba',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mtwara Mjini',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Nanyumbu',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Masasi Township Authority',
            'region_id'=>9,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 10 Ruvuma
            ['district_name'=>'Tunduru',
            'region_id'=>10,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Songea Vijijini',
            'region_id'=>10,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbinga',
            'region_id'=>10,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Songea Mjini',
            'region_id'=>10,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Namtumbo',
            'region_id'=>10,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Nyasa',
            'region_id'=>10,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 11 Iringa
            ['district_name'=>'Iringa Vijijini',
            'region_id'=>11,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mufindi',
            'region_id'=>11,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Iringa Mjini',
            'region_id'=>11,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kilolo',
            'region_id'=>11,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mafinga Township Authority',
            'region_id'=>11,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 12 Mbeya
            ['district_name'=>'Chunya',
            'region_id'=>12,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbeya Vijijini',
            'region_id'=>12,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kyela',
            'region_id'=>12,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Rungwe',
            'region_id'=>12,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbarali',
            'region_id'=>12,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbeya Mjini',
            'region_id'=>12,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 13 Singida
            ['district_name'=>'Iramba',
            'region_id'=>13,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Singida',
            'region_id'=>13,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Manyoni',
            'region_id'=>13,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Singida Mjini',
            'region_id'=>13,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ikungi',
            'region_id'=>13,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mkalama',
            'region_id'=>13,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 14 Tabora 
            ['district_name'=>'Nzega',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Igunga',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Uyui',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Urambo',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Sikonge',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Tabora Mjini',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kaliua',
            'region_id'=>14,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 15 Rukwa
            ['district_name'=>'Kalambo',
            'region_id'=>15,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Sumbawanga Vijijini',
            'region_id'=>15,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Nkasi',
            'region_id'=>15,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Sumbawanga Mjini',
            'region_id'=>15,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 16 Kigoma
            ['district_name'=>'Kibondo',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kasulu',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kigoma Vijijini',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kigoma Municipal-Ujiji',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Uvinza',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Buhigwe',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kakonko',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kasulu Township Authority',
            'region_id'=>16,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 17 Shinyanga
            ['district_name'=>'Shinyanga Mjini',
            'region_id'=>17,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kishapu',
            'region_id'=>17,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Shinyanga Vijijini',
            'region_id'=>17,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kahama',
            'region_id'=>17,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kahama Township Authority',
            'region_id'=>17,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 18 Kagera
            ['district_name'=>'Karagwe',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Bukoba Vijijini',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Muleba',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Biharamulo',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ngara',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Bukoba Mjini',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Missenyi',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kyerwa',
            'region_id'=>18,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 19 Mwanza
            ['district_name'=>'Ukerewe',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Magu',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Nyamagana',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kwimba',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Sengerema',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ilemela',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Misungwi',
            'region_id'=>19,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 20 Mara
            ['district_name'=>'Tarime',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Serengeti',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Musoma',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Bunda',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Rorya',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Butiama',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Musoma Municipal',
            'region_id'=>20,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 21 Manyara
            ['district_name'=>'Babati',
            'region_id'=>21,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Hanang',
            'region_id'=>21,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbulu',
            'region_id'=>21,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Simanjiro',
            'region_id'=>21,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kiteto',
            'region_id'=>21,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Babati Mjini',
            'region_id'=>21,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 22 Njombe
            ['district_name'=>'Njombe Mjini',
            'region_id'=>22,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>"Wanging'ombe",
            'region_id'=>22,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Makete',
            'region_id'=>22,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Njombe Vijijini',
            'region_id'=>22,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Ludewa',
            'region_id'=>22,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Makambako Township Authority',
            'region_id'=>22,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 23 Katavi
            ['district_name'=>'Mpanda Mjini',
            'region_id'=>23,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mpanda Vijijini',
            'region_id'=>23,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mlele',
            'region_id'=>23,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 24 Simiyu
            ['district_name'=>'Bariadi',
            'region_id'=>24,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Itilima',
            'region_id'=>24,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Meatu',
            'region_id'=>24,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Maswa',
            'region_id'=>24,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Busega',
            'region_id'=>24,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 25 Geita
            ['district_name'=>'Geita',
            'region_id'=>25,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>"Nyang'wale",
            'region_id'=>25,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbogwe',
            'region_id'=>25,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Bukombe',
            'region_id'=>25,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Chato',
            'region_id'=>25,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 26 Kaskazini Unguja
            ['district_name'=>'Kaskazini A',
            'region_id'=>26,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kaskazini B',
            'region_id'=>26,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 27 Kusini Unguja
            ['district_name'=>'Kati',
            'region_id'=>27,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Kusini',
            'region_id'=>27,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 28 Mjini Magharibi
            ['district_name'=>'Magharibi',
            'region_id'=>28,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mjini',
            'region_id'=>28,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 29 Kaskazini Pemba
            ['district_name'=>'Wete',
            'region_id'=>29,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Micheweni',
            'region_id'=>29,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 30 Kusini Pemba
            ['district_name'=>'Chake Chake',
            'region_id'=>30,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mkoani',
            'region_id'=>30,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],

            // 31 Songwe
            ['district_name'=>'Ileje',
            'region_id'=>31,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Mbozi',
            'region_id'=>31,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Momba',
            'region_id'=>31,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
            ['district_name'=>'Songwe',
            'region_id'=>31,
           'created_at'=>Carbon::now(),
           'updated_at'=>Carbon::now(),
            ],
        ];
        foreach ($districts as $district) {
            DB::table('districts')->insert($district);
        }
    }
}
