<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class RegionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $regions=[
            ['region_name'=>'Dodoma',
             'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Arusha',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),    
            ],
            ['region_name'=>'Kilimanjaro',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Tanga',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Morogoro',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Pwani',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Dar-es-salaam',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Lindi',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Mtwara',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Ruvuma',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Iringa',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Mbeya',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Singida',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Tabora',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Rukwa',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Kigoma',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Shinyanga',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Kagera',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Mwanza',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Mara',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Manyara',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Njombe',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Katavi',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Simiyu',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Geita',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Kaskazini Unguja',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Kusini Unguja',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Mjini Magharibi',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Kaskazini Pemba',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Kusini Pemba',
            'created_at'=>Carbon::now(),
            'updated_at'=>Carbon::now(),
            ],
            ['region_name'=>'Songwe',
            'created_at'=>Carbon::now(),
             'updated_at'=>Carbon::now(),
            ],
        ];
        foreach ($regions as $region) {
            DB::table('regions')->insert($region);
        }
    }
}
